# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/contrib-stretch64'

  config.vm.network 'forwarded_port', guest: 8081, host: 8081

  config.librarian_puppet.placeholder_filename = '.keep'

  ####### Install Puppet Agent #######
  config.vm.provision 'shell', path: './bootstrap.sh'

  ####### Provision #######
  config.vm.provision 'puppet' do |puppet|
    puppet.options = '--verbose --debug'
    puppet.module_path = ['site', 'modules']
  end
end
